CRITICAL - 2022-03-23 03:28:10 --> Invalid file: login.php
#0 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
#1 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#2 C:\xampp\htdocs\CI4-CRUD\app\Views\templates\content.php(2): view('login')
#3 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('templates/conte...', Array, true)
#6 C:\xampp\htdocs\CI4-CRUD\app\Views\templates\wrapper.php(3): view('templates/conte...')
#7 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#9 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('templates/wrapp...', Array, true)
#10 C:\xampp\htdocs\CI4-CRUD\app\Controllers\Login.php(16): view('templates/wrapp...', Array)
#11 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(832): App\Controllers\Login->index()
#12 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#13 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\CI4-CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\CI4-CRUD\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2022-03-23 03:29:12 --> Invalid file: login.php
#0 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
#1 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#2 C:\xampp\htdocs\CI4-CRUD\app\Views\templates\content.php(2): view('login')
#3 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('templates/conte...', Array, true)
#6 C:\xampp\htdocs\CI4-CRUD\app\Views\templates\wrapper.php(3): view('templates/conte...')
#7 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#9 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('templates/wrapp...', Array, true)
#10 C:\xampp\htdocs\CI4-CRUD\app\Controllers\Login.php(16): view('templates/wrapp...', Array)
#11 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(832): App\Controllers\Login->index()
#12 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#13 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\CI4-CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\CI4-CRUD\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2022-03-23 03:46:32 --> Invalid file: login.php
#0 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
#1 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#2 C:\xampp\htdocs\CI4-CRUD\app\Views\templates\content.php(2): view('login')
#3 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('templates/conte...', Array, true)
#6 C:\xampp\htdocs\CI4-CRUD\app\Views\templates\wrapper.php(3): view('templates/conte...')
#7 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#9 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('templates/wrapp...', Array, true)
#10 C:\xampp\htdocs\CI4-CRUD\app\Controllers\Login.php(16): view('templates/wrapp...', Array)
#11 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(832): App\Controllers\Login->index()
#12 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#13 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\CI4-CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\CI4-CRUD\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2022-03-23 03:46:47 --> Invalid file: login.php
#0 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
#1 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#2 C:\xampp\htdocs\CI4-CRUD\app\Views\templates\content.php(2): view('login')
#3 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('templates/conte...', Array, true)
#6 C:\xampp\htdocs\CI4-CRUD\app\Views\templates\wrapper.php(3): view('templates/conte...')
#7 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#9 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('templates/wrapp...', Array, true)
#10 C:\xampp\htdocs\CI4-CRUD\app\Controllers\Login.php(16): view('templates/wrapp...', Array)
#11 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(832): App\Controllers\Login->index()
#12 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#13 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\CI4-CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\CI4-CRUD\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2022-03-23 03:47:10 --> Invalid file: login.php
#0 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
#1 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#2 C:\xampp\htdocs\CI4-CRUD\app\Views\templates\content.php(2): view('login')
#3 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('templates/conte...', Array, true)
#6 C:\xampp\htdocs\CI4-CRUD\app\Views\templates\wrapper.php(3): view('templates/conte...')
#7 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#9 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('templates/wrapp...', Array, true)
#10 C:\xampp\htdocs\CI4-CRUD\app\Controllers\Login.php(16): view('templates/wrapp...', Array)
#11 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(832): App\Controllers\Login->index()
#12 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#13 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\CI4-CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\CI4-CRUD\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2022-03-23 03:48:08 --> Invalid file: login.php
#0 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
#1 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('login', Array, true)
#2 C:\xampp\htdocs\CI4-CRUD\app\Views\templates\content.php(2): view('login')
#3 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('templates/conte...', Array, true)
#6 C:\xampp\htdocs\CI4-CRUD\app\Views\templates\wrapper.php(3): view('templates/conte...')
#7 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\CI4-CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#9 C:\xampp\htdocs\CI4-CRUD\system\Common.php(1089): CodeIgniter\View\View->render('templates/wrapp...', Array, true)
#10 C:\xampp\htdocs\CI4-CRUD\app\Controllers\Login.php(16): view('templates/wrapp...', Array)
#11 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(832): App\Controllers\Login->index()
#12 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#13 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\CI4-CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\CI4-CRUD\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#16 {main}
ERROR - 2022-03-23 20:35:43 --> Unknown column 'users.deleted_at' in 'where clause'
CRITICAL - 2022-03-23 20:35:44 --> Unknown column 'users.deleted_at' in 'where clause'
#0 C:\xampp\htdocs\CI4-CRUD\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\CI4-CRUD\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\CI4-CRUD\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\CI4-CRUD\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI4-CRUD\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI4-CRUD\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\CI4-CRUD\app\ThirdParty\myth-auth\src\Authentication\LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\CI4-CRUD\app\ThirdParty\myth-auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 C:\xampp\htdocs\CI4-CRUD\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI4-CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CI4-CRUD\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-03-23 20:37:22 --> Can't create table `mahasiswadb`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR - 2022-03-23 20:40:04 --> Unknown column 'users.deleted_at' in 'where clause'
CRITICAL - 2022-03-23 20:40:04 --> Unknown column 'users.deleted_at' in 'where clause'
#0 C:\xampp\htdocs\CI4-CRUD\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\CI4-CRUD\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\CI4-CRUD\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\CI4-CRUD\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI4-CRUD\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI4-CRUD\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\CI4-CRUD\app\ThirdParty\myth-auth\src\Authentication\LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\CI4-CRUD\app\ThirdParty\myth-auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 C:\xampp\htdocs\CI4-CRUD\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI4-CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CI4-CRUD\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-03-23 20:40:27 --> Unknown column 'email' in 'where clause'
CRITICAL - 2022-03-23 20:40:27 --> Unknown column 'email' in 'where clause'
#0 C:\xampp\htdocs\CI4-CRUD\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\CI4-CRUD\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\CI4-CRUD\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\CI4-CRUD\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CI4-CRUD\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CI4-CRUD\system\Validation\Validation.php(292): CodeIgniter\Validation\Rules->is_unique('rizalanditama21...', 'email', Array, NULL)
#6 C:\xampp\htdocs\CI4-CRUD\system\Validation\Validation.php(157): CodeIgniter\Validation\Validation->processRules('email', 'email', 'rizalanditama21...', Array, Array)
#7 C:\xampp\htdocs\CI4-CRUD\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\CI4-CRUD\app\ThirdParty\myth-auth\src\Controllers\AuthController.php(161): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\CI4-CRUD\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\CI4-CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\CI4-CRUD\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
ERROR - 2022-03-23 21:08:12 --> Can't create table `mahasiswadb`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR - 2022-03-23 21:15:13 --> Can't create table `mahasiswadb`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR - 2022-03-23 21:19:40 --> Can't create table `mahasiswadb`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR - 2022-03-23 21:21:38 --> Can't create table `mahasiswadb`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR - 2022-03-23 21:23:06 --> Can't create table `mahasiswadb`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR - 2022-03-23 21:35:30 --> Can't create table `mahasiswadb`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR - 2022-03-23 21:37:09 --> Can't create table `mahasiswadb`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR - 2022-03-23 21:43:02 --> Can't create table `mahasiswadb`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed")
ERROR - 2022-03-23 22:07:32 --> Can't create table `mahasiswadb`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed")
